export const unoGameABI = [
  {
    type: "function",
    name: "createGame",
    inputs: [
      { name: "creator", type: "address" },
      { name: "isBot", type: "bool" },
    ],
    outputs: [{ name: "gameId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createGame",
    inputs: [
      { name: "creator", type: "address" },
      { name: "isBot", type: "bool" },
      { name: "isPrivate", type: "bool" },
      { name: "gameCodeHash", type: "bytes32" },
      { name: "maxPlayers", type: "uint256" },
    ],
    outputs: [{ name: "gameId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deleteGame",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getGamesByCreator",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPublicNotStartedGames",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "joinGame",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "joinee", type: "address" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "startGame",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dealCards",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "count", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commitOpening",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "value", type: "uint256" },
      { name: "sigs", type: "bytes[]" },
      { name: "chosenColor", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "drawCard",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "playCard",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "handIndex", type: "uint256" },
      { name: "claimedValue", type: "uint256" },
      { name: "sigs", type: "bytes[]" },
      { name: "chosenColor", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getGameState",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      { name: "players", type: "address[]" },
      { name: "currentPlayer", type: "address" },
      { name: "turn", type: "uint8" },
      { name: "direction", type: "int8" },
      { name: "pot", type: "uint256" },
      { name: "buyIn", type: "uint256" },
      { name: "phase", type: "uint8" },
      { name: "topValue", type: "uint256" },
      { name: "activeColor", type: "uint8" },
      { name: "winner", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHandSizes",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [{ name: "out", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDealProgress",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      { name: "dealt", type: "uint16" },
      { name: "total", type: "uint16" },
      { name: "ready", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMyHandHandles",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [{ name: "out", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOpeningHandle",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  // ── Megapot jackpot ─────────────────────────────────────────────────────
  {
    type: "function",
    name: "enterJackpot",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimGameJackpot",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getGameJackpot",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      { name: "ticketIds", type: "uint256[]" },
      { name: "players", type: "address[]" },
      { name: "entered", type: "bool" },
      { name: "claimed", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "JackpotEntered",
    inputs: [
      { name: "gameId", type: "uint256", indexed: true },
      { name: "ticketCount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "JackpotSkipped",
    inputs: [
      { name: "gameId", type: "uint256", indexed: true },
      { name: "reason", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "JackpotClaimed",
    inputs: [
      { name: "gameId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerJoined",
    inputs: [
      { name: "gameId", type: "uint256", indexed: true },
      { name: "player", type: "address", indexed: true },
    ],
    anonymous: false,
  },
] as const;
