[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC}"
base = "${BASE_RPC}"
